# Generated by Django 2.0.4 on 2018-05-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseexamine',
            name='dis_adopt_text',
            field=models.TextField(default='', verbose_name='不通过理由'),
        ),
        migrations.AddField(
            model_name='realnameexamine',
            name='dis_adopt_text',
            field=models.TextField(default='', verbose_name='不通过理由'),
        ),
    ]
