# Generated by Django 2.0.4 on 2018-04-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0002_userinfo_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='AntifraudMiGuan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64)),
                ('id_card', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('msg', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='FinanceInvestment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64)),
                ('id_card', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('msg', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TelecomRealName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64)),
                ('id_card', models.CharField(max_length=64)),
                ('mobile', models.CharField(max_length=64)),
                ('data', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('msg', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo')),
            ],
        ),
    ]
