# Generated by Django 2.0.4 on 2018-04-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0003_antifraudmiguan_financeinvestment_telecomrealname'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecentSearchRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField(auto_now_add=True)),
                ('service', models.CharField(max_length=64)),
                ('service_chinese', models.CharField(max_length=64)),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo')),
            ],
        ),
    ]
