# Generated by Django 2.0.4 on 2018-04-28 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0005_auto_20180426_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=64, verbose_name='手机号'),
        ),
    ]
