# Generated by Django 2.0.4 on 2018-04-28 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0006_auto_20180428_0222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='antifraudmiguan',
            options={'verbose_name_plural': '蜜罐查询记录'},
        ),
        migrations.AlterModelOptions(
            name='financeinvestment',
            options={'verbose_name_plural': '个人对外投资查询记录'},
        ),
        migrations.AlterModelOptions(
            name='telecomrealname',
            options={'verbose_name_plural': '运营商三要素查询记录'},
        ),
        migrations.AddField(
            model_name='antifraudmiguan',
            name='order_num',
            field=models.CharField(default=0, max_length=64, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='financeinvestment',
            name='order_num',
            field=models.CharField(default=0, max_length=64, verbose_name='订单号'),
        ),
        migrations.AddField(
            model_name='telecomrealname',
            name='order_num',
            field=models.CharField(default=0, max_length=64, verbose_name='订单号'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='data',
            field=models.TextField(verbose_name='查询返回数据'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='查询时间'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='id_card',
            field=models.CharField(max_length=64, verbose_name='被查询人身份证'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='mobile',
            field=models.CharField(max_length=64, verbose_name='被查询人手机号'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='msg',
            field=models.CharField(max_length=64, verbose_name='查询结果'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='real_name',
            field=models.CharField(max_length=64, verbose_name='被查询人姓名'),
        ),
        migrations.AlterField(
            model_name='antifraudmiguan',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='查询人-手机号'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='data',
            field=models.TextField(verbose_name='查询返回数据'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='查询时间'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='id_card',
            field=models.CharField(max_length=64, verbose_name='被查询人身份证'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='msg',
            field=models.CharField(max_length=64, verbose_name='查询结果'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='real_name',
            field=models.CharField(max_length=64, verbose_name='被查询人姓名'),
        ),
        migrations.AlterField(
            model_name='financeinvestment',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='查询人-手机号'),
        ),
        migrations.AlterField(
            model_name='rechargerecords',
            name='amount',
            field=models.PositiveIntegerField(verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='rechargerecords',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='充值日期'),
        ),
        migrations.AlterField(
            model_name='rechargerecords',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='用户-电话号码'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='data',
            field=models.TextField(verbose_name='查询返回数据'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='查询时间'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='id_card',
            field=models.CharField(max_length=64, verbose_name='被查询人身份证'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='mobile',
            field=models.CharField(max_length=64, verbose_name='被查询人手机号'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='msg',
            field=models.CharField(max_length=64, verbose_name='查询结果'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='real_name',
            field=models.CharField(max_length=64, verbose_name='被查询人姓名'),
        ),
        migrations.AlterField(
            model_name='telecomrealname',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='查询人-手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册日期'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='invest_score',
            field=models.PositiveIntegerField(default=30, verbose_name='个人对外投资消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='miguan_score',
            field=models.PositiveIntegerField(default=20, verbose_name='蜜罐数据消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score',
            field=models.PositiveIntegerField(default=0, verbose_name='剩余积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel_score',
            field=models.PositiveIntegerField(default=10, verbose_name='运营商三要素消耗积分'),
        ),
    ]
