# Generated by Django 2.0.4 on 2018-04-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0007_auto_20180428_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='角色名称')),
            ],
            options={
                'verbose_name_plural': '角色管理',
            },
        ),
        migrations.CreateModel(
            name='ServiceInterFace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=32, verbose_name='服务名称')),
                ('url', models.CharField(max_length=64, verbose_name='接口地址')),
            ],
            options={
                'verbose_name_plural': '接口权限管理',
            },
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name_plural': '用户管理'},
        ),
        migrations.AddField(
            model_name='role',
            name='service',
            field=models.ManyToManyField(to='data_system.ServiceInterFace', verbose_name='对应权限'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='role',
            field=models.ForeignKey(default=None, on_delete=True, to='data_system.Role', verbose_name='角色'),
        ),
    ]
