# Generated by Django 2.0.4 on 2018-04-30 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0009_auto_20180430_1231'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Role',
            new_name='UserRole',
        ),
    ]
