# Generated by Django 2.0.4 on 2018-04-30 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0010_auto_20180430_1232'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRole',
            new_name='Role',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='role',
        ),
    ]
