# Generated by Django 2.0.4 on 2018-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0012_userinfo_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.ManyToManyField(blank=True, to='data_system.ServiceInterFace', verbose_name='对应权限'),
        ),
    ]
