# Generated by Django 2.0.4 on 2018-04-30 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0013_auto_20180430_1259'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(default=None, max_length=364, verbose_name='身份证号'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='id_card_img',
            field=models.ImageField(default=None, upload_to='upload'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='nickname',
            field=models.CharField(default=None, max_length=32, verbose_name='昵称'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='name',
            field=models.CharField(max_length=32, verbose_name='真实姓名'),
        ),
    ]
