# Generated by Django 2.0.4 on 2018-04-30 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0014_auto_20180430_1504'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseExamine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterprise_name', models.CharField(max_length=32, verbose_name='企业名称')),
                ('organization_code', models.CharField(max_length=64, verbose_name='组织机构代码')),
                ('business_license_img', models.ImageField(upload_to='upload', verbose_name='企业营业执照')),
                ('is_adopt', models.BooleanField(default=False, verbose_name='是否通过')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '企业认证审核表',
            },
        ),
        migrations.CreateModel(
            name='RealNameExamine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=32, verbose_name='真实姓名')),
                ('id_card', models.CharField(max_length=64, verbose_name='身份证号')),
                ('pros_id_card_img', models.ImageField(upload_to='upload', verbose_name='身份证正面照')),
                ('cons_id_card_img', models.ImageField(upload_to='upload', verbose_name='身份证反面照')),
                ('is_adopt', models.BooleanField(default=False, verbose_name='是否通过')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '实名认证审核表',
            },
        ),
        migrations.AlterModelOptions(
            name='recentsearchrecord',
            options={'verbose_name_plural': '近期查询记录'},
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id_card_img',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='name',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='business_license_img',
            field=models.ImageField(blank=True, default=None, upload_to='upload', verbose_name='企业营业执照'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='cons_id_card_img',
            field=models.ImageField(blank=True, default=None, upload_to='upload', verbose_name='身份证反面照'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='enterprise_name',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='企业名称'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='organization_code',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='组织机构代码'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='pros_id_card_img',
            field=models.ImageField(blank=True, default=None, upload_to='upload', verbose_name='身份证正面照'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='real_name',
            field=models.CharField(blank=True, default=None, max_length=32, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(blank=True, default=None, max_length=64, verbose_name='身份证号'),
        ),
        migrations.AddField(
            model_name='realnameexamine',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo'),
        ),
        migrations.AddField(
            model_name='enterpriseexamine',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo'),
        ),
    ]
