# Generated by Django 2.0.4 on 2018-04-30 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0016_auto_20180430_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='enterpriseexamine',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
        migrations.AddField(
            model_name='realnameexamine',
            name='is_exam',
            field=models.BooleanField(default=False, verbose_name='是否审核'),
        ),
        migrations.AlterField(
            model_name='realnameexamine',
            name='cons_id_card_img',
            field=models.ImageField(blank=True, default=None, upload_to='upload', verbose_name='身份证反面照'),
        ),
        migrations.AlterField(
            model_name='realnameexamine',
            name='pros_id_card_img',
            field=models.ImageField(blank=True, default=None, upload_to='upload', verbose_name='身份证正面照'),
        ),
    ]
