# Generated by Django 2.0.4 on 2018-04-30 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0017_auto_20180430_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enterpriseexamine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='realnameexamine',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
