# Generated by Django 2.0.4 on 2018-05-01 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0018_auto_20180430_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='功能名称')),
                ('switch', models.BooleanField(default=False, verbose_name='开关')),
            ],
            options={
                'verbose_name_plural': '功能开关',
            },
        ),
    ]
