# Generated by Django 2.0.4 on 2018-05-01 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0019_actionswitch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_name', models.CharField(max_length=64, verbose_name='商品名称')),
                ('price', models.PositiveIntegerField(verbose_name='充值金额')),
                ('pay_type', models.CharField(max_length=32, verbose_name='充值方式')),
                ('order_no', models.CharField(max_length=64, verbose_name='订单编号')),
                ('is_success', models.BooleanField(default=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo')),
            ],
            options={
                'verbose_name_plural': '订单管理',
            },
        ),
    ]
