# Generated by Django 2.0.4 on 2018-05-01 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0020_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_no',
            new_name='order_id',
        ),
    ]
