# Generated by Django 2.0.4 on 2018-05-02 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0022_auto_20180502_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realnameexamine',
            name='cons_id_card_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload', verbose_name='身份证反面照'),
        ),
        migrations.AlterField(
            model_name='realnameexamine',
            name='pros_id_card_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload', verbose_name='身份证正面照'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='cons_id_card_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload', verbose_name='身份证反面照'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='身份证号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pros_id_card_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload', verbose_name='身份证正面照'),
        ),
    ]
