# Generated by Django 2.0.4 on 2018-05-02 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0023_auto_20180502_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='business_license_img',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='upload', verbose_name='企业营业执照'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='corporation_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='法人姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='enterprise_name',
            field=models.CharField(blank=True, default=None, max_length=32, null=True, verbose_name='企业名称'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='organization_code',
            field=models.CharField(blank=True, default=None, max_length=64, null=True, verbose_name='组织机构代码'),
        ),
    ]
