# Generated by Django 2.0.4 on 2018-05-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0024_auto_20180502_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.FloatField(verbose_name='充值金额'),
        ),
    ]
