# Generated by Django 2.0.4 on 2018-05-02 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0025_auto_20180502_0036'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='session_key',
            field=models.CharField(default=None, max_length=64, null=True),
        ),
    ]
