# Generated by Django 2.0.4 on 2018-05-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0026_userinfo_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rechargerecords',
            name='amount',
            field=models.FloatField(verbose_name='充值金额'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='score',
            field=models.FloatField(default=0, verbose_name='剩余积分'),
        ),
    ]
