# Generated by Django 2.0.4 on 2018-05-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0027_auto_20180502_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='invest_score',
            field=models.PositiveIntegerField(default=10, verbose_name='个人对外投资消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='miguan_score',
            field=models.PositiveIntegerField(default=12, verbose_name='蜜罐数据消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='tel_score',
            field=models.FloatField(default=2.4, verbose_name='运营商三要素消耗积分'),
        ),
    ]
