# Generated by Django 2.0.4 on 2018-05-03 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0028_auto_20180503_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='公告标题')),
                ('content', models.TextField(verbose_name='公告内容')),
                ('switch', models.BooleanField(default=True, verbose_name='开关')),
                ('date', models.DateTimeField(verbose_name='创建时间')),
            ],
            options={
                'verbose_name_plural': '公告管理',
            },
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='下单时间'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='是否成功'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(max_length=32, verbose_name='充值方式(1=支付宝,2=微信)'),
        ),
    ]
