# Generated by Django 2.0.4 on 2018-05-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0029_auto_20180503_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
    ]
