# Generated by Django 2.0.4 on 2018-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0030_auto_20180503_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='idcard_img_score',
            field=models.FloatField(default=2.4, verbose_name='身份证实名核验及返照'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='idcard_name_score',
            field=models.FloatField(default=2.4, verbose_name='身份中二要素查询'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='switch',
            field=models.BooleanField(default=True, verbose_name='是否显示'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='昵称-手机号'),
        ),
    ]
