# Generated by Django 2.0.4 on 2018-05-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0031_auto_20180505_1452'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardRealNameModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64, verbose_name='被查询人姓名')),
                ('id_card', models.CharField(max_length=64, verbose_name='被查询人身份证')),
                ('data', models.TextField(verbose_name='查询返回数据')),
                ('date', models.DateField(auto_now_add=True, verbose_name='查询时间')),
                ('msg', models.CharField(max_length=64, verbose_name='查询结果')),
                ('user', models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='查询人-手机号')),
            ],
            options={
                'verbose_name_plural': '身份证二要素查询记录',
            },
        ),
    ]
