# Generated by Django 2.0.4 on 2018-05-05 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0032_idcardrealnamemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdCardImgModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('real_name', models.CharField(max_length=64, verbose_name='被查询人姓名')),
                ('id_card', models.CharField(max_length=64, verbose_name='被查询人身份证')),
                ('data', models.TextField(verbose_name='查询返回数据')),
                ('date', models.DateField(auto_now_add=True, verbose_name='查询时间')),
                ('msg', models.CharField(max_length=64, verbose_name='查询结果')),
            ],
            options={
                'verbose_name_plural': '身份证返照查询记录',
            },
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='invest_score',
            field=models.FloatField(default=12, verbose_name='个人对外投资消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='miguan_score',
            field=models.FloatField(default=10, verbose_name='蜜罐数据消耗积分'),
        ),
        migrations.AddField(
            model_name='idcardimgmodel',
            name='user',
            field=models.ForeignKey(on_delete=None, to='data_system.UserInfo', verbose_name='查询人-手机号'),
        ),
    ]
