# Generated by Django 2.0.4 on 2018-05-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0033_auto_20180505_2058'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinterface',
            name='active_name',
            field=models.CharField(default=None, max_length=32, verbose_name='激活名称'),
        ),
        migrations.AlterField(
            model_name='role',
            name='service',
            field=models.ManyToManyField(blank=True, null=True, to='data_system.ServiceInterFace', verbose_name='对应权限'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='idcard_img_score',
            field=models.FloatField(default=7, verbose_name='身份证实名核验及返照消耗积分'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='idcard_name_score',
            field=models.FloatField(default=3, verbose_name='身份中二要素查询消耗积分'),
        ),
    ]
