# Generated by Django 2.0.4 on 2018-05-06 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_system', '0035_auto_20180505_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentsearchrecord',
            name='service_id',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
    ]
